name: inventory build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Unit Testing
        run: echo Testing

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86_64
          # - x86_amd64
          # - amd64
          # - amd64_x86
    environment: Production
    needs: testing
    steps:
      - uses: actions/checkout@v4

      - name: Configure build toolchains for ${{ matrix.arch }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'      
          distribution: 'graalvm' 
          github-token: ${{ secrets.TOKEN }}

      - name: Get GraalVM environments
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Build JavaFX/GluonFX Project
        run: |
          mvn package clean
          mvn gluonfx:build

      - name: Zip Target
        run: |
          Compress-Archive -Path target/* -Destination inventory_management_system_${{ matrix.arch }}.zip

      - name: Upload zip to artifact
        uses: actions/upload-artifact@v2
        with:
          name: inventory_management_system_${{ matrix.arch }}
          path: inventory_management_system_${{ matrix.arch }}.zip
