name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1.2.1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.TOKEN }}
          native-image-job-reports: 'true'

      - name: Build GluonFX
        run: |
          mvn gluonfx:build

      # - name: Build and run HelloWorld.java
      #   run: |
      #     echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
      #     javac HelloWorld.java
      #     native-image HelloWorld
      #     ./helloworld
      
      # - name: Upload binary
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: helloworld-${{ matrix.os }}
      #     path: helloworld*